Bartosz Podrygajło RPiS lista 11

In [210]:
import numpy as np
import pandas as pd

In [211]:
df = pd.read_csv('deca2015.csv',decimal =',')
df

zawodnik kraj  punkty  100 m  w dal   kula  wzwyĹĽ  400 m  \
0              Ashton Eaton  USA    9045  10.23   7.88  14.52    201  45.00   
1             Damian Warner  CAN    8695  10.31   7.65  14.44    204  47.30   
2             Rico Freimuth  GER    8561  10.51   7.51  15.50    195  47.82   
3            Ilya Shkurenev  RUS    8538  11.01   7.50  14.09    210  47.88   
4            Larbi Bourrada  ALG    8461  10.83   7.51  13.73    207  47.60   
5              Kai Kazmirek  GER    8448  10.90   7.40  14.27    210  46.83   
6          Michael Schrader  GER    8418  10.78   7.71  14.32    195  47.13   
7                Kurt Felix  GRN    8302  11.02   7.66  15.02    210  49.89   
8          Oleksiy Kasyanov  UKR    8262  10.73   7.58  14.25    201  48.13   
9               Maicel Uibo  EST    8245  11.25   7.13  14.45    213  50.24   
10            Adam Helcelet  CZE    8234  11.09   7.29  15.30    204  49.66   
11             Pieter Braun  NED    8114  11.11   7.29  13.90    204  48.24   
12           Bastien Auzeil  FRA    8093  11.22   7.26  15.38    201  48.66   
13  Thomas van der Plaetsen  BEL    8035  11.44   7.42  13.83    213  50.28   
14              Zach Ziemek  USA    8006  10.81   7.57  13.38    204  49.89   
15         Akihiko Nakamura  JPN    7745  10.86   7.26  11.67    195  47.81   
16          Pawel Wiesiolek  POL    7705  11.07   7.08  13.50    198  48.55   
17             Pau Tonnesen  ESP    7606  11.26   7.21  13.74    204  50.24   
18            Janek Oiglane  EST    7581  11.51   6.78  14.43    192  50.95   
19           Keisuke Ushiro  JPN    7532  11.51   6.73  14.93    189  50.85   
20              Jorge Urena  ESP    6858  10.99   7.30  12.74    201  49.17   
21         Niels Pittomvils  BEL    6678  11.39   6.86  12.77    192  49.45   

    110 ppł   dysk  tyczka  oszczep  1500 m  miejsce  
0     13.69  43.34     520    63.63  257.52        1  
1     13.63  44.99     480    63.50  271.51        2  
2     13.91  50.17     480    60.61  277.05        3  
3     14.27  44.53     520    60.99  264.98        4  
4     14.26  41.53     480    63.82  256.61        5  
5     14.39  40.08     520    62.55  275.61        6  
6     14.19  44.58     460    62.09  262.30        7  
7     14.58  45.95     450    63.41  272.57        8  
8     13.96  45.84     480    49.35  271.80        9  
9     15.01  43.69     510    64.51  265.53       10  
10    14.20  42.90     490    63.07  277.65       11  
11    14.37  42.09     490    56.95  272.46       12  
12    14.71  42.63     510    55.14  277.92       13  
13    14.76  43.01     530    55.23  287.38       14  
14    15.29  44.19     520    56.50  296.66       15  
15    14.72  33.48     470    53.57  256.36       16  
16    14.82  41.55     450    54.18  279.31       17  
17    15.12  45.28     480    60.42  333.73       18  
18    15.33  40.94     460    68.51  283.06       19  
19    15.43  46.85     470    56.52  283.51       20  
20    14.41  35.20       0    53.17  282.21       21  
21    15.09  39.90       0    52.96  267.40       22

## Zadanie 2.

$$\Theta = (X X^T)^{-1} X Y^T$$

In [212]:
X = df.drop(['punkty','zawodnik','kraj','miejsce'], axis = 1).values
X = X.T
X

array([[  10.23,   10.31,   10.51,   11.01,   10.83,   10.9 ,   10.78,
          11.02,   10.73,   11.25,   11.09,   11.11,   11.22,   11.44,
          10.81,   10.86,   11.07,   11.26,   11.51,   11.51,   10.99,
          11.39],
       [   7.88,    7.65,    7.51,    7.5 ,    7.51,    7.4 ,    7.71,
           7.66,    7.58,    7.13,    7.29,    7.29,    7.26,    7.42,
           7.57,    7.26,    7.08,    7.21,    6.78,    6.73,    7.3 ,
           6.86],
       [  14.52,   14.44,   15.5 ,   14.09,   13.73,   14.27,   14.32,
          15.02,   14.25,   14.45,   15.3 ,   13.9 ,   15.38,   13.83,
          13.38,   11.67,   13.5 ,   13.74,   14.43,   14.93,   12.74,
          12.77],
       [ 201.  ,  204.  ,  195.  ,  210.  ,  207.  ,  210.  ,  195.  ,
         210.  ,  201.  ,  213.  ,  204.  ,  204.  ,  201.  ,  213.  ,
         204.  ,  195.  ,  198.  ,  204.  ,  192.  ,  189.  ,  201.  ,
         192.  ],
       [  45.  ,   47.3 ,   47.82,   47.88,   47.6 ,   46.83,   47.13,
     

In [213]:
Y = df['punkty'].values
Y

array([9045, 8695, 8561, 8538, 8461, 8448, 8418, 8302, 8262, 8245, 8234,
       8114, 8093, 8035, 8006, 7745, 7705, 7606, 7581, 7532, 6858, 6678], dtype=int64)

In [214]:
Theta = np.linalg.inv(X.dot(X.T)).dot(X).dot(Y.T)
Theta

array([  86.83455605,  827.75214645,  102.0432961 ,    7.31738267,
        -61.48810369,   30.58214867,   15.14780602,    1.6025744 ,
         16.92405392,   -6.19359834])

Kolumna predict - wartości wyliczone za pomocą modelu  
Kolumna values - punkty

In [215]:
res = pd.DataFrame()
res['predict'] = Theta.T.dot(X)
res['values'] = Y
res

predict  values
0   8986.918654    9045
1   8546.055878    8695
2   8461.678710    8561
3   8529.875669    8538
4   8470.935180    8461
5   8417.304650    8448
6   8580.928625    8418
7   8547.250477    8302
8   8213.904478    8262
9   8208.070558    8245
10  8214.933986    8234
11  8082.621977    8114
12  8156.767790    8093
13  8120.610977    8035
14  8084.346624    8006
15  7659.850949    7745
16  7653.711115    7705
17  7624.600920    7606
18  7588.695374    7581
19  7485.427044    7532
20  6870.205984    6858
21  6640.880738    6678

##Zadanie 1

In [216]:
X = df.drop(['punkty','zawodnik','kraj','miejsce'], axis = 1).values
X = X.T
X = np.vstack((np.ones_like(X[0]),X))
X

array([[   1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,
           1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,
           1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,
           1.  ],
       [  10.23,   10.31,   10.51,   11.01,   10.83,   10.9 ,   10.78,
          11.02,   10.73,   11.25,   11.09,   11.11,   11.22,   11.44,
          10.81,   10.86,   11.07,   11.26,   11.51,   11.51,   10.99,
          11.39],
       [   7.88,    7.65,    7.51,    7.5 ,    7.51,    7.4 ,    7.71,
           7.66,    7.58,    7.13,    7.29,    7.29,    7.26,    7.42,
           7.57,    7.26,    7.08,    7.21,    6.78,    6.73,    7.3 ,
           6.86],
       [  14.52,   14.44,   15.5 ,   14.09,   13.73,   14.27,   14.32,
          15.02,   14.25,   14.45,   15.3 ,   13.9 ,   15.38,   13.83,
          13.38,   11.67,   13.5 ,   13.74,   14.43,   14.93,   12.74,
          12.77],
       [ 201.  ,  204.  ,  195.  ,  210.  ,  207.  ,  210.  ,  195.  ,
     

In [217]:
Theta = np.linalg.inv(X.dot(X.T)).dot(X).dot(Y.T)
Theta

array([  8.96649620e+03,  -2.27338339e+02,   2.32916348e+02,
         6.69363669e+01,   1.21338947e+01,  -6.54523526e+01,
        -8.71755941e+01,   2.09015760e+01,   1.76504826e+00,
         1.43668519e+01,  -5.76647414e+00])

In [218]:
res = pd.DataFrame()
res['predict'] = Theta.T.dot(X)
res['values'] = Y
res

predict  values
0   9001.124711    9045
1   8696.448789    8695
2   8556.479635    8561
3   8520.576879    8538
4   8478.143503    8461
5   8460.707562    8448
6   8437.627256    8418
7   8356.364372    8302
8   8265.252658    8262
9   8233.549865    8245
10  8221.064926    8234
11  8126.002326    8114
12  8088.640933    8093
13  7997.342626    8035
14  7987.246566    8006
15  7744.026063    7745
16  7765.900956    7705
17  7611.838698    7606
18  7573.052667    7581
19  7522.626354    7532
20  6857.791178    6858
21  6660.191476    6678

##Zadanie 3

Średnia

In [219]:
df.mean()

punkty     8052.818182
100 m        10.992273
w dal         7.344545
kula         14.098182
wzwyĹĽ       201.954545
400 m        48.707727
110 ppł      14.551818
dysk         42.850909
tyczka      444.090909
oszczep      59.121818
1500 m      276.051364
miejsce      11.500000
dtype: float64

Wariancja

In [220]:
df.var()

punkty     321763.965368
100 m           0.123514
w dal           0.090216
kula            0.856101
wzwyĹĽ          48.331169
400 m           2.241990
110 ppł         0.274606
dysk           13.219190
tyczka      21244.372294
oszczep        24.483377
1500 m        271.927727
miejsce        42.166667
dtype: float64

##Zadanie 4

In [221]:
Z = df.drop(['zawodnik','kraj','miejsce','punkty'], axis = 1).apply(lambda x: (x - np.mean(x))/np.std(x),axis =0)
Z

100 m     w dal      kula     wzwyż     400 m   110 ppł      dysk  \
0  -2.220008  1.824658  0.466621 -0.140535 -2.534502 -1.683303  0.137686   
1  -1.987020  1.040891  0.378124  0.301147 -0.962284 -1.800495  0.602183   
2  -1.404549  0.563816  1.550711 -1.023898 -0.606826 -1.253599  2.060423   
3   0.051628  0.529739 -0.009051  1.184510 -0.565812 -0.550447  0.472687   
4  -0.472596  0.563816 -0.407288  0.742828 -0.757212 -0.569979 -0.371854   
5  -0.268731  0.188971  0.190068  1.184510 -1.283564 -0.316063 -0.780048   
6  -0.618213  1.245352  0.245378 -1.023898 -1.078492 -0.706703  0.486762   
7   0.080752  1.074968  1.019728  1.184510  0.808170  0.055045  0.872436   
8  -0.763831  0.802354  0.167943 -0.140535 -0.394919 -1.155939  0.841470   
9   0.750593 -0.731102  0.389186  1.626191  1.047420  0.894921  0.236215   
10  0.284616 -0.185873  1.329468  0.301147  0.650948 -0.687171  0.013820   
11  0.342864 -0.185873 -0.219231  0.301147 -0.319726 -0.355127 -0.214206   
12  0.663223 -0.288104  1.417965 -0.140535 -0.032625  0.308961 -0.062189   
13  1.303941  0.257125 -0.296666  1.626191  1.074763  0.406621  0.044786   
14 -0.530843  0.768277 -0.794463  0.301147  0.808170  1.441816  0.376972   
15 -0.385225 -0.288104 -2.686089 -1.023898 -0.613662  0.328493 -2.638038   
16  0.226369 -0.901486 -0.661717 -0.582217 -0.107818  0.523813 -0.366224   
17  0.779717 -0.458488 -0.396226  0.301147  1.047420  1.109773  0.683822   
18  1.507805 -1.923790  0.367062 -1.465580  1.532757  1.519944 -0.537947   
19  1.507805 -2.094174  0.920169 -1.907261  1.464400  1.715264  1.125798   
20 -0.006619 -0.151797 -1.502440 -0.140535  0.315997 -0.276999 -2.153834   
21  1.158323 -1.651176 -1.469253 -1.465580  0.507398  1.051177 -0.830721   

      tyczka   oszczep    1500 m  
0   0.533057  0.932540 -1.150224  
1   0.252165  0.905649 -0.281878  
2   0.252165  0.307838  0.061984  
3   0.533057  0.386443 -0.687189  
4   0.252165  0.971842 -1.206707  
5   0.533057  0.709137 -0.027395  
6   0.111719  0.613983 -0.853534  
7   0.041495  0.887032 -0.216085  
8   0.252165 -2.021349 -0.263878  
9   0.462834  1.114572 -0.653051  
10  0.322388  0.816701  0.099226  
11  0.322388 -0.449251 -0.222912  
12  0.462834 -0.823659  0.115984  
13  0.603280 -0.805042  0.703157  
14  0.533057 -0.542336  1.279158  
15  0.181942 -1.148421 -1.222224  
16  0.041495 -1.022240  0.202260  
17  0.252165  0.268535  3.580057  
18  0.111719  1.941992  0.435019  
19  0.181942 -0.538199  0.462950  
20 -3.118542 -1.231163  0.382261  
21 -3.118542 -1.274603 -0.536982

## Zadanie 5
Macież korelacji Z

In [222]:
C = Z.corr()
C

100 m     w dal      kula     wzwyż     400 m   110 ppł      dysk  \
100 m    1.000000 -0.811194 -0.073924 -0.074017  0.820196  0.818384 -0.160450   
w dal   -0.811194  1.000000  0.156556  0.452777 -0.670768 -0.758916  0.249473   
kula    -0.073924  0.156556  1.000000  0.110883  0.018441 -0.250943  0.761141   
wzwyĹĽ   -0.074017  0.452777  0.110883  1.000000 -0.044109 -0.210682  0.074059   
400 m    0.820196 -0.670768  0.018441 -0.044109  1.000000  0.798137  0.066395   
110 ppł  0.818384 -0.758916 -0.250943 -0.210682  0.798137  1.000000 -0.164162   
dysk    -0.160450  0.249473  0.761141  0.074059  0.066395 -0.164162  1.000000   
tyczka  -0.190203  0.321954  0.467843  0.339961 -0.156204 -0.135329  0.461970   
oszczep -0.137289  0.151960  0.473673  0.235999 -0.073576 -0.135386  0.262594   
1500 m   0.367926 -0.260571  0.039473  0.034693  0.556608  0.472368  0.228565   

           tyczka   oszczep    1500 m  
100 m   -0.190203 -0.137289  0.367926  
w dal    0.321954  0.151960 -0.260571  
kula     0.467843  0.473673  0.039473  
wzwyĹĽ    0.339961  0.235999  0.034693  
400 m   -0.156204 -0.073576  0.556608  
110 ppł -0.135329 -0.135386  0.472368  
dysk     0.461970  0.262594  0.228565  
tyczka   1.000000  0.384360  0.027140  
oszczep  0.384360  1.000000 -0.085601  
1500 m   0.027140 -0.085601  1.000000

Cztery pary najbardziej skorelowanych konkurencji

In [223]:
C.apply(lambda x: np.abs(x)).unstack().order()[-18:-10]

110 ppł  400 m      0.798137
400 m    110 ppł    0.798137
w dal    100 m      0.811194
100 m    w dal      0.811194
110 ppł  100 m      0.818384
100 m    110 ppł    0.818384
400 m    100 m      0.820196
100 m    400 m      0.820196
dtype: float64